country=['america','vietnam','thailand','indonesia','korea']
print("Print list: ",country)
print("Printing the last index of the list: ",country[-1])
country[1]='laos'
print("Change 2nd to Laos: ", country)
country.append('china')
print("Append China: ",country)
country.insert(2, 'cambodia')
print("Insert 2nd to list: ",country)
del country[0]
print("del the first one in list: ",country)
country.pop(1)
print("pop 1st value from list: ",country)
country.remove('korea')
print('remove value "korea" from list: ',country)
print("temporary sorted: ",sorted(country))
print("Reverse temporaty sorted",sorted(country,reverse=True))
country.sort()
print("Permanently sort: ",country)
country.sort(reverse=True)
print("Reverse permanently sort: ",country)
country.reverse()
print("Reverse list: ",country)
country.reverse()
print("Reverse reversed order: ",country)
print("Length of list: ",len(country))